version: "3.3"

services:
  proxy_app:
    container_name: proxy_app
    build:
      context: .
      dockerfile: Dockerfile
    # depends_on:
      # - prometheus
    ports:
      - "8000:8000"
    command: sh -c "uvicorn app.main:app --reload --port=8000 --host=0.0.0.0"
    env_file:
      - .env
      - db.env
    depends_on:
      - database
      - prometheus
      - grafana
    links:
     - redisdb
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$DB_USERNAME --password=$$DB_ROOT_PASSWORD
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart:  always
  
  database:
    image: mysql:latest
    container_name: database
    env_file:
      - db.env
    volumes:
      - database_data:/var/lib/mysql
    ports:
      - "3307:3306"
    restart: always
  
  redisdb:
    image: redis:latest
    container_name: redisdb
    ports:
      - "6379:6379"
    restart: always
    env_file:
      - db.env
    volumes: 
      - ./cache:/data
  
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - proxy_app
  
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    links:
      - mysql_exporter
    depends_on:
      - database
      - mysql_exporter
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
  
  # tool to connect to mysql instance, and allow prometheus to collect mysql stats
  mysql_exporter:
    image: quay.io/prometheus/mysqld-exporter
    container_name: mysqld-exporter
    restart: unless-stopped
    command:
     - "--mysqld.username=root:myRootPassword123"
     - "--mysqld.address=localhost:3306"
    networks:
      - prometheus_mysql_exporter
    volumes:
      - ./.my.cnf:/cfg/.my.cnf

volumes:
  database_data:
  grafana-storage:
  redisdb:
    driver: local

networks:
  prometheus_mysql_exporter:
    driver: bridge