version: "3.3"

services:
  proxy_app:
    build:
      context: .
      dockerfile: Dockerfile
    # depends_on:
      # - prometheus
    ports:
      - "8000:8000"
    command: sh -c "uvicorn app.main:app --reload --port=8000 --host=0.0.0.0"
    env_file:
      - .env
      - db.env
    depends_on:
      - database
      - prometheus
      - grafana
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$DB_USERNAME --password=$$DB_PASSWORD
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
  
  database:
    image: mysql:latest
    env_file:
      - db.env
    volumes:
      - database_data:/var/lib/mysql
    ports:
      - "3307:3306"
    restart: always
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    env_file:
      - db.env
  
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - proxy_app
  
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    links:
      - mysql_exporter
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
  
  # tool to connect to mysql instance, and allow prometheus to collect mysql stats
  mysql_exporter:
    image: prom/mysqld-exporter
    links:
      - database
    ports:
      - '9104:9104'
    depends_on:
      - database
    environment:
      - DATA_SOURCE_NAME="meli_user:meli_password@database:3306/meli_stats"
    command: /bin/mysqld_exporter collect.binlog_size=true collect.info_schema.processlist=true
    networks:
      - prometheus_mysql_exporter

volumes:
  database_data:
  grafana-storage:

networks:
  prometheus_mysql_exporter:
    internal: true