version: "3.3"

services:
  proxy_app:
    container_name: proxy_app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    env_file:
      - db.env
      - .env
    labels:
      # Enable Traefik for this specific service 
      - traefik.enable=true
      # Define de port inside of the Docker service to use
      - traefik.http.services.app.loadbalancer.server.port=8000
      # Make Traefik use this domain in HTTP
      - traefik.http.routers.app-http.entrypoints=http
      - traefik.http.routers.app-http.rule=Host(`localhost`)
      # Use the traefik-public network  (declared below)
      - traefik.docker.network=traefik-public
    networks:
      - traefik-public
    restart: always
  
  streamlit:
    build:
      context: .
      dockerfile: streamlit.Dockerfile
    restart: always
    labels:
      # Enable Traefik for this specific service 
      - traefik.enable=true
      # Define the port inside of the Docker service to use
      - traefik.http.services.streamlit.loadbalancer.server.port=8000
      # Make Traefik use this domain in HTTP
      - traefik.http.routers.streamlit-http.entrypoints=http
      - traefik.http.routers.streamlit-http.rule=Host(`streamlit.localhost`)
      # Use the traefik-public network (declared below)
      - traefik.docker.network=traefik-public
      # Enable HTTP Basic auth, using the middleware created above
      - traefik.http.routers.streamlit-http.middlewares=admin-auth
    networks:
      - traefik-public
  
  panel:
    build:
      context: .
      dockerfile: panel.Dockerfile
    restart: always
    environment:
      - BOKEH_ALLOW_WS_ORIGIN=localhost:8090,panel.localhost
    labels:
      # Enable Traefik for this specific service 
      - traefik.enable=true
      # Define the port inside of the Docker service to use
      - traefik.http.services.panel.loadbalancer.server.port=8000
      # Make Traefik use this domain in HTTP
      - traefik.http.routers.panel-http.entrypoints=http
      - traefik.http.routers.panel-http.rule=Host(`panel.localhost`)
      # Use the traefik-public network (declared below)
      - traefik.docker.network=traefik-public
      # Enable HTTP Basic auth, using the middleware created above
      - traefik.http.routers.panel-http.middlewares=admin-auth
    networks:
      - traefik-public

  database:
    image: mysql:latest
    container_name: database
    env_file:
      - db.env
    volumes:
      - database_data:/var/lib/mysql
    ports:
      - "3307:3306"
    restart: always
    networks:
      - traefik-public
  
  redisdb:
    image: redis:latest
    container_name: redisdb
    ports:
      - "6379:6379"
    restart: always
    env_file:
      - db.env
    volumes: 
      - ./cache:/data
    networks:
      - traefik-public

volumes:
  database_data:
  cache:

networks:
  traefik-public:
    external: true